# Generated by Django 5.0.4 on 2025-04-11 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('id_kh', models.AutoField(primary_key=True, serialize=False)),
                ('ten_kh', models.CharField(max_length=50)),
                ('sdt', models.CharField(max_length=10, unique=True)),
                ('dia_chi', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id_sp', models.AutoField(primary_key=True, serialize=False)),
                ('ten_sp', models.CharField(max_length=100)),
                ('gia', models.IntegerField(unique=True)),
                ('mo_ta', models.TextField()),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('id_dh', models.AutoField(primary_key=True, serialize=False)),
                ('tong_sp', models.IntegerField(default=0)),
                ('tong_tien', models.IntegerField(default=0)),
                ('ngay_dat', models.DateTimeField(auto_now_add=True)),
                ('trang_thai', models.CharField(choices=[('DA_DAT', 'Đã đặt hàng'), ('XAC_NHAN', 'Đã xác nhận và chuẩn bị vận chuyển'), ('DANG_VC', 'Đang vận chuyển'), ('THANH_CONG', 'Nhận hàng và thanh toán thành công'), ('HUY', 'Hủy đơn hàng')], default='DA_DAT', max_length=20)),
                ('id_kh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web_Com.khachhang')),
            ],
        ),
        migrations.CreateModel(
            name='LienHe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nd_lh', models.TextField()),
                ('ngay_lh', models.DateTimeField(auto_now_add=True)),
                ('phan_hoi', models.TextField(blank=True, null=True)),
                ('id_kh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web_Com.khachhang')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietDonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField()),
                ('gia', models.IntegerField(editable=False)),
                ('id_dh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web_Com.donhang')),
                ('id_kh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web_Com.khachhang')),
                ('id_sp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web_Com.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('id_tk', models.AutoField(primary_key=True, serialize=False)),
                ('ten_dn', models.CharField(max_length=50, unique=True)),
                ('mk', models.CharField(max_length=128)),
                ('id_kh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web_Com.khachhang')),
            ],
        ),
    ]
