# Generated by Django 5.0.4 on 2025-04-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Com', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='hinh_anh',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
